apiVersion: v1
kind: Service
metadata:
  name: todoapp
  labels:
    app: todoapp-mongo
spec:
  selector:
    app: todoapp-mongo
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31200