---
- hosts: ansible-server
  become: true

  tasks:
  - name: create docker image using war file
    command: docker build -t todoapp:latest .
    args:
      chdir: /home/ansadmin/kubernetes/todo-app

  - name: create tag to image
    command: docker tag todoapp imarslan/todoapp:latest

  - name: login to dockerhub
    command: cat ~/my_password.txt | docker login --username imarslan --password-stdin
    
  - name: push image on to dockerhub
    command: docker push imarslan/todoapp

  - name: remove docker images form ansible server
    command: docker rmi todoapp:latest imarslan/todoapp
    ignore_errors: yes
