---
- hosts: all
  become: true
  tasks:
  - name: Remove if we have old docker stack
    command: docker stack rm node-todo-app
    ignore_errors: yes

  - name: Remove current docker image
    command: docker rmi -f imarslan/todoapp:latest
    ignore_errors: yes
    register: result
    failed_when:
      - result.rc == 0
      - '"docker" not in result.stdout'
  
  - name: Building docker image
    command: chdir=/home/ansadmin/docker-node-mongo-todo-app docker build -t imarslan/todoapp:latest .
    ignore_errors: yes

  - name: Deploying docker stack
    command: chdir=/home/ansadmin/docker-node-mongo-todo-app docker stack deploy --compose-file docker-compose.yml node-todo-app

