version: '3.3'

services:
  todoapp2:
    image: todoapp:latest
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.todoapp-http.rule=Host(`todoapp2.dev-ops.work`)
        - traefik.http.routers.todoapp-http.entrypoints=http
        - traefik.http.routers.todoapp-http.middlewares=https-redirect
        - traefik.http.routers.todoapp-https.rule=Host(`todoapp2.dev-ops.work`)
        - traefik.http.routers.todoapp-https.entrypoints=https
        - traefik.http.routers.todoapp-https.tls=true
        - traefik.http.routers.todoapp-https.tls.certresolver=le
        - traefik.http.services.todoapp.loadbalancer.server.port=5000

networks:
  traefik-public:
    external: true
